---
- name: Provision of Web instance
  ec2:
    instance_type: "{{ instance_type }}"
    keypair: "{{ keypair }}"
    group: "{{ sg_group }}"
    ec2_region: "{{ ec2_region }}"
    image: "{{ image }}"
    wait: true
    vpc_subnet_id: "{{ vpc_subnet_id }}"
    count: 1
    instance_tags:
       Name: "{{ tag_name }}"
  register: ec2

- name: Set the Instances facts
  set_fact:
    instance_ip: "{{ ec2.instances[0].private_ip }}"

- name: WebServer | Wait for SSH to come up
  local_action: 
    module: wait_for 
    host: "{{ instance_ip }}" 
    port: 22 
    state: started

- name: deploy container
  command: ssh -oStrictHostKeyChecking=no -i "~/salient-base-ami.pem" ec2-user@{{ instance_ip }} sudo docker run -d -p 8080:8080 salientcrgt/jpetstore:{{ build }}
  register: task_result
  until: task_result.rc == 0
  retries: 10
  delay: 2
  ignore_errors: yes

- name: save file with information for dns creation
  blockinfile:
    path: dns_prefix.conf
    create: yes
    block: |
      DNS_PREFIX={{ tag_name }}
      DNS_PORT=80
      INTERNAL_IP={{ instance_ip }}
      INTERNAL_PORT=8080

