---
- name: Provision of Web instance
  ec2:
    instance_type: t2.micro
    keypair: 'salient-base-ami'
    group: "{{ sg_group }}"
    ec2_region: 'us-east-1'
    image: "ami-b55013a3"
    wait: true
    vpc_subnet_id: subnet-cd2a1ae6
    count: 1
    instance_tags:
       Name: jpdocker-{{ env }}
  register: ec2

- name: Set the Instances facts
  set_fact:
    instance_ip: "{{ ec2.instances[0].private_ip }}"

- name: WebServer | Wait for SSH to come up
  local_action: 
    module: wait_for 
    host: "{{ instance_ip }}" 
    port: 22 
    state: started

- name: deploy container
  command: ssh -oStrictHostKeyChecking=no -i "~/salient-base-ami.pem" ec2-user@{{ instance_ip }} sudo docker run -d -p 8080:8080 salientcrgt/jpetstore:{{ build }}
  register: task_result
  until: task_result.rc == 0
  retries: 10
  delay: 1
  ignore_errors: yes

