---
- name: Provision of Web instance
  ec2:
    instance_type: t2.micro
    keypair: 'salient-base-ami'
    group: "{{ web }}"
    ec2_region: 'us-east-1'
    image: "ami-b55013a3"
    wait: true
    vpc_subnet_id: subnet-cd2a1ae6
    count: 1
    instance_tags:
       Name: web-jpetstore
  register: web-instance



