- name: Deploy container
  command: ssh -oStrictHostKeyChecking=no -i "~/salient-base-ami.pem" ec2-user@{{ instance_ip }} sudo docker run -d -p 8080:8080 salientcrgt/jpetstore:{{ build }}
  register: task_result
  until: task_result.rc == 0
  retries: 10
  delay: 2
  ignore_errors: yes

- name: Wait untils the web app is available
  shell: curl --head --silent http://{{ ip }}:8080/jpetstore/
  register: result
  until: result.stdout.find("200 OK") != -1
  retries: 15
  delay: 5