- name: Stop container
  command: ssh -oStrictHostKeyChecking=no -i "~/salient-base-ami.pem" ec2-user@{{ item.private_ip_address }} sudo docker stop $(sudo docker ps -aq)
  register: stop_task_result
  until: stop_task_result.rc == 0
  retries: 10
  delay: 2
  ignore_errors: yes
  with_items: "{{ ec2_facts.instances }}"

- name: Deploy container
  command: ssh -oStrictHostKeyChecking=no -i "~/salient-base-ami.pem" ec2-user@{{ item.private_ip_address }} sudo docker run -d -p 8080:8080 salientcrgt/jpetstore:{{ build }}
  register: task_result
  until: task_result.rc == 0
  retries: 10
  delay: 2
  ignore_errors: yes
  with_items: "{{ ec2_facts.instances }}"

- name: Wait untils the web app is available
  shell: curl --head --silent http://{{ item.private_ip_address }}:8080/jpetstore/actions/Catalog.action
  register: result
  until: result.stdout.find("HTTP/1.1 200 ") != -1
  retries: 25
  delay: 5
  with_items: "{{ ec2_facts.instances }}"
