- name: Deploy container
  command: ssh -oStrictHostKeyChecking=no -i "~/salient-base-ami.pem" ec2-user@{{ item.private_ip_address }} sudo docker run -d -p 8080:8080 salientcrgt/jpetstore:{{ build }}
  register: task_result
  until: task_result.rc == 0
  retries: 10
  delay: 2
  ignore_errors: yes
  with_items: "{{ ec2_facts.instances }}"